---

- hosts: localhost
  name: Create node data model
  gather_facts: no
  vars:
    node: vSRX2
    interfaces:
        - ge-0/0/0
        - ge-0/0/1
    bgp_peers:    
        - is_up: true
          local_as: 65000
    ebgp:
      - {name: ce1, ip: 192.10.1.2, as: 65001, local: vSRX2 }
      - {name: ce2, ip: 192.10.2.2, as: 65002, local: vSRX3 }
      - {name: ce3, ip: 192.10.3.2, as: 65003, local: vSRX2 }
  tasks:
    #- debug: msg={{ interfaces|append_str('.0')}}
#    - set_fact:

    - debug: var=interfaces
    - debug: var=node
    - debug: var=bgp_peers
    - debug: msg={{ bgp_peers|map(attribute='is_up')|list}}
    - debug: msg={{ ebgp|map(attribute='local')|list}}
    - debug: msg={{ ebgp|selectattr('local', 'match', "{{node}}")| list}}