#
# Nodes in the network
#

---

common:
    bgp_asn: 65000

nodes:

  MX1:
    mgmt: 192.10.1.101
    rid:  10.100.1.1
    links:
      ge-0/0/0.0: { ip: 172.10.12.1, remote: MX2 , cost: 10 , vlan: 0}
      ge-0/0/1.0: { ip: 172.10.13.1, remote: MX3 , cost: 10 , vlan: 0}
      ge-0/0/2.0: { ip: 172.10.14.1, remote: MX4 , cost: 10 , vlan: 0}
    bgp:
       ibgp:
         rr: true
         peers:
            - 10.100.2.2
            - 10.100.3.3
            - 10.100.4.4
         af:
            - inet
            - inet-vpn
    ospf:
        network: p2p

  MX2:
    mgmt: 192.10.1.102
    rid:  10.100.2.2
    links:
      ge-0/0/0.0: { ip: 172.10.12.2, remote: MX1 , cost: 10 , vlan: 0}
    bgp:
       ibgp:
         peers:
            - 10.100.1.1
         af:
            - inet
            - inet-vpn
    ospf:
        network: p2p

  MX3:
    mgmt: 192.10.1.103
    rid:  10.100.3.3
    links:
      ge-0/0/0.0: { ip: 172.10.13.3, remote: MX1 , cost: 10 , vlan: 0}
    bgp:
       ibgp:
         peers:
            - 10.100.1.1
         af:
            - inet
            - inet-vpn
    ospf:
        network: p2p

  MX4:
    mgmt: 192.10.1.104
    rid:  10.100.4.4
    links:
      ge-0/0/0.0: { ip: 172.10.14.4, remote: MX1 , cost: 10 , vlan: 0}
    bgp:
       ibgp:
         peers:
            - 10.100.1.1
         af:
            - inet
            - inet-vpn
    ospf:
        network: p2p

