---

hostname: "vSRX2"
router_id: 10.100.3.3
bgp_asn: 65000

interfaces:
 - name: lo0
   tagged: false
   vlans:
    - vlanid: 0
      ipaddr: 10.100.3.3
      netmask: 32
      mpls: false

 - name: ge-0/0/1
   description: "OOB to Ansible Host"
   tagged: false
   vlans:
    - vlanid: 0
      ipaddr: 192.10.1.103
      netmask: 24
      mpls: false

 - name: ge-0/0/2
   description: "vsrx3--ge-0/0/2__vsrx1--ge-0/0/3"
   tagged: false
   vlans:
    - vlanid: 0
      ipaddr: 172.10.13.3
      netmask: 24
      mpls: true

 - name: ge-0/0/3
   description: "vsrx3--ge-0/0/3__vsrx2--ge-0/0/3"
   tagged: false
   vlans:
    - vlanid: 0
      ipaddr: 172.10.23.3
      netmask: 24
      mpls: true
bgp:
 groups:
  - name: "Core-RR"
    type: internal
    localaddress: 10.100.3.3
    afs:
     - inet-vpn
     - inet-unicast
    peers:
     - ip: 10.100.1.1
       description: "Peering to vSRX1"
     - ip: 10.100.2.2
       description: "Peering to vSRX2"

ospf:
 areas:
  - id: 0
    interfaces:
     - name: ge-0/0/2.0
       metric: 100
       type: p2p
       passive: false
     - name: ge-0/0/3.0
       metric: 100
       type: p2p
       passive: false
     - name: lo0.0
       passive: true

ldp:
 interfaces:
  - ge-0/0/2.0
  - ge-0/0/3.0
  - lo0.0 
