---

common:
  bgp_asn: 65000

nodes:
  - name: MX1
    mgmt: 192.10.1.101
    rid: 10.100.1.1

  - name: MX2
    mgmt: 192.10.1.102
    rid: 10.100.2.2
    
  - name: MX3
    mgmt: 192.10.1.103
    rid: 10.100.3.3

  - name: MX4
    mgmt: 192.10.1.104
    rid: 10.100.4.4

links:
  - {left: MX1, left_port: ge-0/0/0, left_ip: 172.10.12.1,
      right: MX2, right_port: ge-0/0/0, right_ip: 172.10.12.2, cost: 10 }

  - {left: MX1, left_port: ge-0/0/1, left_ip: 172.10.13.1,
      right: MX3, right_port: ge-0/0/0, right_ip: 172.10.13.3, cost: 10 }

  - {left: MX1, left_port: ge-0/0/2, left_ip: 172.10.14.1,
      right: MX4, right_port: ge-0/0/0, right_ip: 172.10.14.4, cost: 10 }

bgp:
  rr: [10.100.1.1]
  clients: [10.100.2.2, 10.100.3.3,10.100.4.4]
  af:
    - inet
    - inet-vpn

ospf:
  area: 0
  network: p2p


  
  