---

- name: execute command on JunOS srx device
  gather_facts: no
  connection: local
  hosts: all
  tasks:
    - file: path=lldp_data.csv state=touch

    - junos_command: 
       commands: show lldp neighbors
       display: xml
      register: show
    - set_fact: lldp_output="{{show.output[0]['rpc-reply']}}"
    - set_fact: lldp_neigbour_table="{{ lldp_output["lldp-neighbors-information"]["lldp-neighbor-information"] }}"

    - name: Generate Report for LLDP neigbours
      template: src=ospf-report.j2 dest=./lldp_report.txt