---

- name: execute command on JunOS srx device
  gather_facts: no
  connection: local
  hosts: all
  tasks:
    - junos_command: 
       commands: show version
       display: xml
      register: show
    
    - debug: var=show 
    #var=show.output[0]['rpc-reply']["software-information"]["package-information"].comment

#    - fail: msg="Wrong JunOS Version"
#      when: "not ( version in show.output[0]['rpc-reply']['software-information']['package-information'].comment)"

