

---

common:
    vrf_name: cust1
    rt: 65000:1
    rd: 65000:1

nodes:
  vSRX2:
    links:
      ge-0/0/3.10 : { ip: 192.100.1.1, vlan: 10  }
    bgp:
        ip: 192.100.1.2
        as: 65001
        prefix:
        - 10.100.1.0/24

  vSRX3:
    links:
      ge-0/0/3.10 : { ip: 192.100.2.1, vlan: 10  }
    bgp:
        ip: 192.100.2.2
        as: 65002
        prefix:
        - 10.100.2.0/24

