---
common:
  customer_name: cust1
  rt: '65000:1'
  rd: '65000:1'


links:
- {pe: vMX2, left_port: ge-0/0/2, left_ip: 192.100.1.1,
    ce: ce1, right_port: ge-0/0/0, right_ip: 192.100.1.2, vlan: 10 }
- {pe: vMX3, left_port: ge-0/0/2, left_ip: 192.100.2.1,
    ce: ce2, right_port: ge-0/0/1, right_ip: 192.100.2.2, vlan: 10 }

sites:
- name: ce1
  routing:
   {ip: 192.100.1.2, as: 65001, local: vMX2, prefix: [10.100.1.0/24]}
- name: ce2
  routing:
   {ip: 192.100.2.2, as: 65002, local: vMX3, prefix: [10.100.2.0/24]}

