---

common:
  bgp_asn: 65000

nodes:
  - name: vMX1
    mgmt: 192.10.1.101
    rid: 10.100.1.1

  - name: vMX2
    mgmt: 192.10.1.102
    rid: 10.100.2.2
    
  - name: vMX3
    mgmt: 192.10.1.103
    rid: 10.100.3.3

  - name: vMX4
    mgmt: 192.10.1.104
    rid: 10.100.4.4

  - name: XR5
    mgmt: 192.10.1.105
    rid: 10.100.5.5

links:
  - {left: vMX1, left_port: ge-0/0/2, left_ip: 172.10.12.1,
      right: vMX2, right_port: ge-0/0/0, right_ip: 172.10.12.2, cost: 10 }

  - {left: vMX1, left_port: ge-0/0/3, left_ip: 172.10.13.1,
      right: vMX3, right_port: ge-0/0/0, right_ip: 172.10.13.3, cost: 10 }

  - {left: vMX1, left_port: ge-0/0/4, left_ip: 172.10.14.1,
      right: vMX4, right_port: ge-0/0/0, right_ip: 172.10.14.4, cost: 10 }

  - {left: vMX1, left_port: ge-0/0/5, left_ip: 172.10.15.1, vlan: 40,
      right: XR5, right_port: GigabitEthernet0/0/0/0, right_ip: 172.10.15.5, cost: 10 }

bgp:
  rr: [10.100.1.1]
  clients: [10.100.2.2, 10.100.3.3,10.100.4.4,10.100.5.5]
  af:
    - inet
    - inet-vpn

ospf:
  area: 0
  network: p2p


  
  