---

common:
  bgp_asn: 65000

nodes:
  - name: vSRX1
    mgmt: 192.10.1.101
    rid: 10.100.1.1

  - name: vSRX2
    mgmt: 192.10.1.102
    rid: 10.100.2.2
    
  - name: vSRX3
    mgmt: 192.10.1.103
    rid: 10.100.3.3

links:
  - {left: vSRX1, left_port: ge-0/0/2, left_ip: 172.10.12.1,
      right: vSRX2, right_port: ge-0/0/2, right_ip: 172.10.12.2, cost: 10 }

  - {left: vSRX1, left_port: ge-0/0/3, left_ip: 172.10.13.1,
      right: vSRX3, right_port: ge-0/0/2, right_ip: 172.10.13.3, cost: 10 }

  - {left: vSRX2, left_port: ge-0/0/3, left_ip: 172.10.23.2,
      right: vSRX3, right_port: ge-0/0/3, right_ip: 172.10.23.3, cost: 10 }

bgp:
  rr: [10.100.1.1]
  clients: [10.100.2.2, 10.100.3.3]
  af:
    - inet
    - inet-vpn

ospf:
  area: 0
  network: p2p


  
  