#
# Nodes in the network
#




---

common:
    bgp_asn: 65000

nodes:

  vSRX2:
    mgmt: 192.10.1.102
    rid:  10.100.2.2
    links:
      ge-0/0/4.10 : { ip: 192.168.1.1, remote: ce1, vlan: 10  }
    bgp:
      ebgp:
        peers:
            ce1:  
                ip: 192.168.1.2 
                as: 65001 
                prefix:
                    - 192.200.1.0/24
                    - 192.200.10.0/24

            

  vSRX3:
    mgmt: 192.10.1.103
    rid:  10.100.3.3
    links:
      ge-0/0/4.20 : { ip: 192.168.2.1, remote: ce2, vlan: 20  }
      ge-0/0/4.30 : { ip: 192.168.3.1, remote: ce3, vlan: 30  }
    bgp:
      ebgp:
        peers:
            ce2:  
                ip: 192.168.2.2 
                as: 65002 
                prefix:
                    - 192.200.2.0/24

            ce3:  
                ip: 192.168.3.2 
                as: 65003 
                prefix:
                    - 192.200.3.0/24
                    - 192.200.30.0/24

            

