---

- name: Enable LLDP on all routers in the topology and validate it
  gather_facts: no
  connection: local
  hosts: all
  tasks:
    - name: GET LLDP output
      napalm_get_facts:
        hostname: "{{ inventory_hostname }}"
        username: "{{ ansible_user }}"
        dev_os: junos
        password: "{{ ansible_ssh_pass }}"
        filter: 
          - lldp_neighbors
          - bgp_neighbors

    - debug: var=vars
