---
- hosts: localhost
  name: Create node data model
  gather_facts: no
  tags: [ model ]
  vars_files:
  - "{{model|default('eBGP-model.yml')}}"
  tasks:
  - name: Create per-node data model from fabric data model
    template: src=ebgp-service.j2 dest=./ebgp-node.yml
  - debug: var=vars

#  - debug: var=vars

- name: Generate Configuration for all routers
  gather_facts: no
  connection: local
  hosts: all
  tags: [ template ]
  tasks:
    - include_vars: "./ebgp-node.yml"
    - file: path=config  state=directory
      run_once: true
    - name: Generate Configuration
      template: src=./jnpr-ebgp.j2 dest=config/{{inventory_hostname}}-ebgp-config.txt
      when: "inventory_hostname in nodes.keys()" 